---
- hosts: test-servers
  user: dpnipat1
  become: yes
  become_method: sudo
  tasks:
  - name: install multiple RPM's
    yum: name=httpd,ntp,nginx state=present

  - name: Start httpd service
    service: name=httpd state=started enabled=yes

  - name: copy the standard index file
    copy: src=/tmp/index.html dest=/var/www/html/index.html mode=0664

  - name: Add apaache port 80 to iptable rule
    command: /usr/sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache on port 80"
    command: iptables-save
